<?php

namespace AppBundle\Repository;

/**
 * ContactRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactRepository extends \Doctrine\ORM\EntityRepository
{
    public function findWithCompany($id) {
        // si SQL
        // https://www.doctrine-project.org/projects/doctrine-orm/en/2.6/reference/native-sql.html#native-sql

        $dql = "SELECT c, s
                FROM AppBundle\Entity\Contact c
                LEFT JOIN c.company s
                WHERE c.id = :id";

        return $this->getEntityManager()->createQuery($dql)
            ->setParameter('id', $id)
            ->getOneOrNullResult();
    }
}
